name: travel_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.0.4
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: ^1.1.0
  get_it: ^7.2.0
  json_annotation: ^4.3.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/

  fonts:
    - family: 'Noto Kufi'
      fonts:
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoKufiArabic/NotoKufiArabic-Thin.ttf
          weight: 100